pipeline
{

agent {
  label 'DevServer'
}

parameters {
  choice choices: ['dev', 'prod'], name: 'select_env'
}

tools {
  maven 'mymaven'
}


stages{

  stage('build'){
    steps{
      sh 'mvn clean package -DskipTests=true'

    }
 

  }
stage('test')
    {
    parallel
          {
          stage('test-A')
          {
            agent { label 'DevServer'}
           steps{
                 echo 'this is test A'
                 sh "mvn test"
                }
          }
          stage('test-B')
          {
            agent { label 'DevServer'}
            steps{
                  echo 'this is test B'
                  sh "mvn test"
                 }
            }
          }
          post{
            success{
              dir("webapp/target/")
              {
                stash name: "maven-build", includes: "*.war"
              }
            }
          }
      }
      stage("deploy-dev")
      {
        when { expression {params.select_env == 'dev'}
        beforeAgent true}
        agent { label 'DevServer'}
        
        steps{
          dir("var/www/html")
          {
            unstash "maven-build"
          }
          sh """
          cd /var/www/html/
          jar  -xvf webapp.war
          """
        }
      }


}

}