pipeline
{

agent {
  label 'DevServer'
}

parameters {
  choice choices: ['dev', 'prod'], name: 'select env'
}

tools {
  maven 'mymaven'
}


stages{

  stage('build'){
    steps{
      sh 'mvn clean package -DskipTests=true'

    }
 

  }
stage('test'){
  parallel{
    stage('test-A'){
      steps{
        echo 'this is test A'
      }
    }
    stage('test-B'){
      steps{
        echo 'this is test B'
      }
    }
  }
}


}

}